eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://self.yun888.xyz:7001/eureka/
  instance:
    hostname: self.yun888.xyz

server:
  port: 7001
