eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://yun888.xyz:7001/eureka/
  instance:
    hostname: yun888.xyz

server:
  port: 7001
