eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-store-member
    prefer-ip-address: true

info:
  app:
    name: jackzhan-cloud-store

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: club.jackzhan.cloudstore.entities
  # 原生配置
  configuration:
    interceptors: com.baomidou.mybatisplus.plugins.PaginationInterceptor
  global-config:
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true

server:
  port: 9991
  tomcat:
    uri-encoding: UTF-8
  context-path: /member


logging:
  level:
    club:
      jackzhan:
        cloudstore:
          mapper:
            debug

spring:
  application:
    name: cloud-store-member
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-store-member?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin
    # 连接池配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 30
      ######Druid监控配置######
      #是否启用StatFilter默认值true
      web-stat-filter.enabled: true
      #IP 白名单
      stat-view-servlet.allow: 127.0.0.1
      #IP 黑名单
      #spring.datasource.druid.stat-view-servlet.deny=192.168.0.101
      #监控地址,默认 /druid/*
      stat-view-servlet.url-pattern: /druid/*
      #哪些资源配置监控：主要只静态资源和监控地址本身
      WebStatFilter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet.login-username: druid
      stat-view-servlet.login-password: druid123123

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
